### PR TITLE
nsdl 3.0

### PR DESCRIPTION
**Pull request by cxy-uestc**
Submit README, ISSUE_TEMPLATE with submissions questions from Microsoft HDC

### CODE REVIEW

**Comment by vathpela** [comment]
I think you meant to open an issue rather than a PR?

**Comment by cxy-uestc** [comment]
Maybe what I described is not very accurate, I meant to make a submission to shim-review and let microsoft staff sign for my UEFI.     
**what he said is followed**, “ Since this is a SHIM, you will need to submit to the SHIM review board here: https://github.com/rhboot/shim-review 
Once your submission is approved by the SHIM review board, we will be able to approve and sign.”

**Comment by cxy-uestc** [comment]
Hi, vathpela 
As part of the Shim signing process as requested by Microsoft, I am kindly asking you to approve our shim to get it signed by Microsoft.
Are there any issues or missings in our submission that prevent its build being reproduced? Please let us know if any...

**Comment by cxy-uestc** [comment]
Hi, vathpela 
As part of the Shim signing process as requested by Microsoft, I am kindly asking you to approve our shim to get it signed by Microsoft.
Are there any issues or missings in our submission that prevent its build being reproduced? Please let us know if any...

**Comment by cxy-uestc** [comment]
@vathpela

**Comment by cxy-uestc** [comment]
Hi, cyphermox
Could you take a review for my pull request?  No reply for long time.
@cyphermox

**Comment by cyphermox** [comment]
Please file an *issue* at https://github.com/rhboot/shim-review/issues/new. Follow the instructions there; to point to this branch (your https://github.com/cxy-uestc/shim-review/tree/nsdl-3.0).

**Pull request closed without merging**
