### PR TITLE
Shim for Newstart Desktop Linux V3

### PR DESCRIPTION
**Pull request by cxy-uestc**
pull request for Issues: #62

### CODE REVIEW

**Comment by cxy-uestc** [comment]
@cyphermox  @vathpela   Could you take a review for my request?  Thank you very much.

**Comment by cxy-uestc** [comment]
@cyphermox @vathpela Could you take a review for my request? Thank you very much.

**Comment by cyphermox** [comment]
We don't need a pull request for this; we review your branch directly. This one (and PRs) are only if changes need to be made to the templates.

**Comment by cxy-uestc** [comment]
OK，I get it. Thank you!

**Pull request closed without merging**
