### PR TITLE
Add REVIEW.md

### PR DESCRIPTION
**Pull request by nicholasbishop**
The text here is imported from https://github.com/rhboot/shim/wiki/reviewer-guidelines

I think including this in the repo will help people find it, and also by putting it in git we can do code review on changes, which is harder in the wiki format.

If this is merged we should delete the wiki page's current text and just link to the new location.

### CODE REVIEW

**Comment by frozencemetery** [comment]
I didn't notice this PR before making some changes to the wiki, so apologies for that.  Should be an easy sync, though.

**Comment by steve-mcintyre** [comment]
I'm more tempted to update the in-source docs to point at the wiki, I'll be honest. Then we can continue to update the docs for guidelines **without** having to commit changes in the main shim source. How does that sound?

**Comment by nicholasbishop** [comment]
> Then we can continue to update the docs for guidelines without having to commit changes in the main shim source.

This PR is into shim-review, not shim. IMO it should be fine to update review guidelines in this repo, and there are some significant advantages to using a real repo rather than the wiki:
1. PR review. Changes to the wiki just silently appear there, rather than going through the PR process.
2. Community edit access. Anyone can make a PR, but wikis usually have a more restrictive access controls. If you do open up the wiki to [allow non-collaborator access](https://docs.github.com/en/communities/documenting-your-project-with-wikis/changing-access-permissions-for-wikis), extra work is needed to moderate the wiki.

**Comment by steve-mcintyre** [comment]
> > Then we can continue to update the docs for guidelines without having to commit changes in the main shim source.
> 
> This PR is into shim-review, not shim.

Ah, now I understand you better. Doh! :-)

>IMO it should be fine to update review guidelines in this repo, and there are some significant advantages to using a real repo rather than the wiki:
> 
>     1. PR review. Changes to the wiki just silently appear there, rather than going through the PR process.
> 
>     2. Community edit access. Anyone can make a PR, but wikis usually have a more restrictive access controls. If you do open up the wiki to [allow non-collaborator access](https://docs.github.com/en/communities/documenting-your-project-with-wikis/changing-access-permissions-for-wikis), extra work is needed to moderate the wiki.

Fair points, yes. I've been making some more tweaks in the wiki recently, expanding on stuff. I'll push changes across here shortly...

**Comment by steve-mcintyre** [comment]
Just opened #344 for that now...

**Comment by steve-mcintyre** [comment]
Closing this - basically the same text is now in docs/reviewer-guidelines.md via a roundabout route

**Pull request closed without merging**
